ingress: https://arbeid.dev.nav.no/arbeid/registrering-ny
basePath: /arbeid/registrering-ny
mocking: enabled
dekorator:
  url: https://dekoratoren.dev.nav.no/
  env: dev
loginservice:
  url: https://loginservice.dev.nav.no/login
  wellKnown: https://navtestb2c.b2clogin.com/navtestb2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
amplitude:
  apiKey: 2f190e67f31d7e4719c5ff048ad3d3e6
  endPoint: amplitude.nav.no/collect
sentry:
  dsn: https://b2f662d8ed7a42b29f465f365e25832f@sentry.gc.nav.no/118
pamJanzzUrl: https://arbeidsplassen.dev.nav.no/pam-janzz/rest
startRegistreringUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/startregistrering/
fullforRegistreringUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/startregistrering/
fullforRegistreringSykmeldtUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/startregistrersykmeldt/
reaktiveringUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/reaktivering/
sisteArbeidsforholdUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/sistearbeidsforhold/
opprettOppgaveUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/oppgave/
kontaktinformasjonUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/person/kontaktinfo
ptoProxyUrl: http://pto-proxy.pto.svc.cluster.local/proxy/
dittNAVUrl: https://www.dev.nav.no/person/dittnav
dialogUrl: https://www.dev.nav.no/arbeid/dialog
featureToggles:
  server: https://unleash.nais.io/api/client/features?tag[]=simple:arbeidssokerregistrering
  client: https://arbeid.dev.nav.no/arbeid/registrering-ny/api/features
