ingress: https://www.nav.no/arbeid/registrering
basePath: /arbeid/registrering
mocking: disabled
nodeEnv: production
dekorator:
  url: https://dekoratoren.nav.no/
  env: prod
loginservice:
  url: https://loginservice.nav.no/login
amplitude:
  apiKey: b0bccdd4dd75081606ef7bcab668a7ed
  endPoint: amplitude.nav.no/collect
sentry:
  dsn: https://b2f662d8ed7a42b29f465f365e25832f@sentry.gc.nav.no/118
pamJanzzUrl: https://arbeidsplassen.nav.no/pam-janzz/rest
startUrl: https://www.nav.no/arbeid/registrering/start
startRegistreringUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/startregistrering/
fullforRegistreringUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/startregistrering/
fullforRegistreringSykmeldtUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/startregistrersykmeldt/
reaktiveringUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/startreaktivering/
sisteArbeidsforholdUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/sistearbeidsforhold/
opprettOppgaveUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/oppgave/
kontaktinformasjonUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/person/kontaktinfo
ptoProxyUrl: http://pto-proxy.pto.svc.cluster.local/proxy/
dittNAVUrl: https://www.nav.no/person/dittnav
dagpengesoknadUrl: https://www.nav.no/arbeid/dagpenger/soknad-veileder
dialogUrl: https://www.nav.no/arbeid/dialog
featureToggles:
  server: https://unleash.nais.io/api/client/features?tag[]=simple:arbeidssokerregistrering
  client: https://www.nav.no/arbeid/registrering/api/features
hentProfileringUrl: http://pto-proxy.pto.svc.cluster.local/proxy/veilarbregistrering/api/profilering/
